//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiz_lizo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fiz_lizo()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id { get; set; }
        public string familia { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_rozjdenia { get; set; }
        public string telephone { get; set; }
        public int pasport_id { get; set; }
    
        public virtual pasport pasport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
