//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RussianCosmeticDBEntities : DbContext
    {
        public RussianCosmeticDBEntities()
            : base("name=RussianCosmeticDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<controller> controller { get; set; }
        public virtual DbSet<fiz_lizo> fiz_lizo { get; set; }
        public virtual DbSet<kont_lizo> kont_lizo { get; set; }
        public virtual DbSet<okaz_usluga> okaz_usluga { get; set; }
        public virtual DbSet<pasport> pasport { get; set; }
        public virtual DbSet<rukovoditel> rukovoditel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ur_lizo> ur_lizo { get; set; }
        public virtual DbSet<usluga> usluga { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    }
}
