//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ur_lizo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ur_lizo()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id { get; set; }
        public string nazvanie_companii { get; set; }
        public string adress { get; set; }
        public string inn { get; set; }
        public string rasch_schot { get; set; }
        public string bik { get; set; }
        public string email { get; set; }
        public string parol { get; set; }
        public int rukovoditel_id { get; set; }
        public int kont_lizo_id { get; set; }
    
        public virtual kont_lizo kont_lizo { get; set; }
        public virtual rukovoditel rukovoditel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
