//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usluga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usluga()
        {
            this.okaz_usluga = new HashSet<okaz_usluga>();
            this.controller = new HashSet<controller>();
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id { get; set; }
        public string naimenovanie { get; set; }
        public decimal stoimost { get; set; }
        public System.DateTime srok_vipolnenia { get; set; }
        public System.DateTime srednee_otklonenie { get; set; }
        public int kod_uslugi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<okaz_usluga> okaz_usluga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<controller> controller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
