//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianCosmetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zakaz()
        {
            this.usluga = new HashSet<usluga>();
        }
    
        public int id { get; set; }
        public System.DateTime data_sozdania { get; set; }
        public bool status { get; set; }
        public Nullable<System.TimeSpan> vremya_vipolnenia { get; set; }
        public Nullable<decimal> stoimost { get; set; }
        public int klient_id { get; set; }
    
        public virtual fiz_lizo fiz_lizo { get; set; }
        public virtual ur_lizo ur_lizo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usluga> usluga { get; set; }
    }
}
